# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
PAYPAL_SANDBOX: "FALSE"
PAYPAL_USERNAME: "George_api1.iscopeapp.com"
PAYPAL_PASSWORD: "BBQB43GHKE5388HC"
PAYPAL_SIGNATURE: "Atf9YmFKDY0dZH8ODT5lwnT34fAvAutg12GtuCwdlTUloTcLkBszN7yT"
USERNAME_MAIL: "subscription@iscope2c.com"
MAIL_REPLYTO: "support@iscope2c.com"
DB_PROD_USER: "iscopepayment"
DB_PROD_DB: "iscopepaymentdb"
DB_PROD_PASSWORD: "9VNF6ZNW9WBEU7mF"
DB_PROD_HOST: "iscopepaymentdb.cp07cfp0fjsl.us-east-1.rds.amazonaws.com"
REDACTED: "AKIAJB65OCRT6VPKYBGA"
REDACTED: "gOWMvEp9KVwtMhE4Cwubdyr9XB1EEE6kL3ZFmeXW"
FOG_DIRECTORY: "iscopepayment"
SIDEKIQ_USERNAME: "admin"
SIDEKIQ_PASSWORD: "sumeram7"


